language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      env: CHECK_OLD_GPGME=1
      env: R_CODECOV=1
      apt_packages: gnupg
    - os: linux
      dist: precise
      sudo: false
      env: CHECK_OLD_GPGME=1
      apt_packages: gnupg2
    - os: linux
      dist: trusty
      sudo: required
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode8
      brew_packages: gpgme
      latex: false
    - os: osx
      osx_image: xcode8
      disable_homebrew: true
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages:
      - libgpgme11-dev
      - valgrind

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
